name: pwa-demo
type: typo3
docroot: public
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
  - api.pwa-demo
additional_fqdns: []
mariadb_version: "10.2"
provider: default
hooks:
  post-start:
    - exec: /var/www/html/.ddev/import-if-empty.sh
    - exec: composer install --ignore-platform-reqs
    - exec: cd front && npm init nuxt-typo3 --answers "$(< ./recommended.json)"
    - exec: cd front && yarn build
    - exec: cd front && yarn start&
use_dns_when_possible: true
